Nama = input("Nama \t\t\t: ")
Nim = input("NIM\t\t\t: ")
KelasParalel = input("Kelas Paralel \t\t: ")
TempatTanggalLahir = input("Tempat, Tanggal Lahir\t: ")
Alamat = input("Alamat\t\t\t: ")
Hobby = input("Hobby\t\t\t: ")
nohp = input("No HP\t\t\t: ")
print ("")
print("Nama \t\t\t : ", Nama)
print("NIM \t\t\t : ", Nim)
print("Kelas Paralel \t\t : ", KelasParalel)
print("Tempat, Tanggal Lahir \t : ", TempatTanggalLahir)
print("Alamat \t\t\t : ", Alamat)
print("Hobby \t\t\t : ", Hobby)
print("No HP \t\t\t : ", nohp)
