r = float(input())
t = float(input())
volume = 22 * r * r * t / 7
luas = 2 * 22 * r * (r + t) / 7
keliling = 2 * 22 * r / 7
print(f"Volume = {volume:.2f}")
print(f"Luas = {luas:.2f}")
print(f"Keliling = {keliling:.2f}")
r, t = map(float, input().split())
volume = 22 * r * r * t /7
luas = 2 * 22 * r * (r + t) / 7
keliling = 2 * 22 * r / 7
print(f"Volume = {volume:.2f}")
print(f"Luas = {luas:.2f}")
print(f"Keliling = {keliling:.2f}")