a, b, i, j, x, y = map(float, input().split())
print("%.3f" %((a - b) * (i / j) - (x + y)))
a, b = map(float, input().split())
i, j = map(float, input().split())
x, y = map(float, input().split())
print("%.3f" % ((a - b) * (i / j) - (x + y)))